from PySide2.QtCore import (QCoreApplication, QMetaObject, QRect)
from PySide2.QtWidgets import (QCheckBox, QComboBox, QLabel,QLineEdit, QMainWindow, QMenu, QMenuBar,QPushButton,  QStatusBar, QWidget)

#Klasa z całym ui
class Ui_WtykaFTP(object):
    def setupUi(self, WtykaFTP):
        if not WtykaFTP.objectName():
            WtykaFTP.setObjectName(u"WtykaFTP")
        WtykaFTP.setFixedSize(400, 430)
        self.centralwidget = QWidget(WtykaFTP)
        self.centralwidget.setObjectName(u"centralwidget")
        self.photosLabel = QLabel(self.centralwidget)
        self.photosLabel.setObjectName(u"photosLabel")
        self.photosLabel.setGeometry(QRect(10, 10, 381, 16))
        self.filePhotosEdit = QLineEdit(self.centralwidget)
        self.filePhotosEdit.setPlaceholderText("Wybierz folder ze zdjęciami")
        self.filePhotosEdit.setObjectName(u"filePhotosEdit")
        self.filePhotosEdit.setGeometry(QRect(10, 40, 311, 20))
        self.photosButton = QPushButton(self.centralwidget)
        self.photosButton.setObjectName(u"photosButton")
        self.photosButton.setGeometry(QRect(330, 40, 21, 23))
        self.epsgLabel1 = QLabel(self.centralwidget)
        self.epsgLabel1.setObjectName(u"epsgLabel1")
        self.epsgLabel1.setGeometry(QRect(10, 70, 81, 16))
        self.coordsEdit1 = QLineEdit(self.centralwidget)
        self.coordsEdit1.setPlaceholderText("Kod EPSG")
        self.coordsEdit1.setObjectName(u"coordsEdit1")
        self.coordsEdit1.setGeometry(QRect(90, 68, 71, 20))
        self.geodeicNetworkLabel = QLabel(self.centralwidget)
        self.geodeicNetworkLabel.setObjectName(u"geodeicNetworkLabel")
        self.geodeicNetworkLabel.setGeometry(QRect(10, 90, 381, 16))
        self.fileEditLine2 = QLineEdit(self.centralwidget)
        self.fileEditLine2.setPlaceholderText("Wybierz plik z punktami osnowy")
        self.fileEditLine2.setObjectName(u"fileEditLine2")
        self.fileEditLine2.setGeometry(QRect(10, 110, 311, 20))
        self.geodNetButton = QPushButton(self.centralwidget)
        self.geodNetButton.setObjectName(u"geodNetButton")
        self.geodNetButton.setGeometry(QRect(330, 110, 21, 23))
        self.coordsEdit2 = QLineEdit(self.centralwidget)
        self.coordsEdit2.setObjectName(u"coordsEdit2")
        self.coordsEdit2.setGeometry(QRect(90, 138, 71, 20))
        self.coordsEdit2.setPlaceholderText("Kod EPSG")
        self.epsgLabel2 = QLabel(self.centralwidget)
        self.epsgLabel2.setObjectName(u"epsgLabel2")
        self.epsgLabel2.setGeometry(QRect(10, 140, 81, 16))
        self.orientationLabel = QLabel(self.centralwidget)
        self.orientationLabel.setObjectName(u"orientationLabel")
        self.orientationLabel.setGeometry(QRect(10, 160, 381, 16))
        self.epsglabel3 = QLabel(self.centralwidget)
        self.epsglabel3.setObjectName(u"epsglabel3")
        self.epsglabel3.setGeometry(QRect(10, 180, 91, 16))
        self.coordsEdit3 = QLineEdit(self.centralwidget)
        self.coordsEdit3.setPlaceholderText("Kod EPSG")
        self.coordsEdit3.setObjectName(u"coordsEdit3")
        self.coordsEdit3.setGeometry(QRect(100, 178, 71, 20))
        self.chooseQualityOrient = QComboBox(self.centralwidget)
        self.chooseQualityOrient.addItem("")
        self.chooseQualityOrient.addItem("")
        self.chooseQualityOrient.addItem("")
        self.chooseQualityOrient.addItem("")
        self.chooseQualityOrient.addItem("")
        self.chooseQualityOrient.setObjectName(u"chooseQualityOrient")
        self.chooseQualityOrient.setGeometry(QRect(120, 208, 80, 22))
        self.allignmentLabel = QLabel(self.centralwidget)
        self.allignmentLabel.setObjectName(u"allignmentLabel")
        self.allignmentLabel.setGeometry(QRect(10, 210, 101, 16))
        self.productsLabel = QLabel(self.centralwidget)
        self.productsLabel.setObjectName(u"productsLabel")
        self.productsLabel.setGeometry(QRect(10, 240, 381, 16))
        self.cloudPointBox = QCheckBox(self.centralwidget)
        self.cloudPointBox.setChecked(True)
        self.cloudPointBox.setObjectName(u"cloudPointBox")
        self.cloudPointBox.setGeometry(QRect(10, 260, 71, 21))
        self.chooseQualityCloudPoint = QComboBox(self.centralwidget)
        self.chooseQualityCloudPoint.addItem("")
        self.chooseQualityCloudPoint.addItem("")
        self.chooseQualityCloudPoint.addItem("")
        self.chooseQualityCloudPoint.addItem("")
        self.chooseQualityCloudPoint.addItem("")
        self.chooseQualityCloudPoint.setObjectName(u"chooseQualityCloudPoint")
        self.chooseQualityCloudPoint.setGeometry(QRect(90, 260, 80, 22))
        self.modelBox = QCheckBox(self.centralwidget)
        self.modelBox.setChecked(True)
        self.modelBox.setObjectName(u"modelBox")
        self.modelBox.setGeometry(QRect(10, 290, 70, 18))
        self.chooseQualityModel = QComboBox(self.centralwidget)
        self.chooseQualityModel.addItem("")
        self.chooseQualityModel.addItem("")
        self.chooseQualityModel.addItem("")
        self.chooseQualityModel.addItem("")
        self.chooseQualityModel.addItem("")
        self.chooseQualityModel.setObjectName(u"chooseQualityModel")
        self.chooseQualityModel.setGeometry(QRect(90, 290, 80, 22))
        #self.rasterBox = QCheckBox(self.centralwidget)
        #self.rasterBox.setObjectName(u"rasterBox")
        #self.rasterBox.setGeometry(QRect(10, 320, 70, 18))
        self.runButton = QPushButton(self.centralwidget)
        self.runButton.setObjectName(u"runButton")
        self.runButton.setGeometry(QRect(260, 380, 131, 40))
        WtykaFTP.setCentralWidget(self.centralwidget)

        self.retranslateUi(WtykaFTP)

        QMetaObject.connectSlotsByName(WtykaFTP)

    def retranslateUi(self, WtykaFTP):
        WtykaFTP.setWindowTitle(QCoreApplication.translate("WtykaFTP", u"Wtyczka FTP - Projekt", None))
        self.photosLabel.setText(QCoreApplication.translate("WtykaFTP",
                                                            u"Zdjęcia --------------------------------------------------------------------------------------",
                                                            None))
        self.photosButton.setText(QCoreApplication.translate("WtykaFTP", u"...", None))
        self.epsgLabel1.setText(QCoreApplication.translate("WtykaFTP", u"Wybierz układ:", None))
        self.geodeicNetworkLabel.setText(QCoreApplication.translate("WtykaFTP",
                                                                    u"Osnowa --------------------------------------------------------------------------------------",
                                                                    None))
        self.geodNetButton.setText(QCoreApplication.translate("WtykaFTP", u"...", None))
        self.epsgLabel2.setText(QCoreApplication.translate("WtykaFTP", u"Wybierz układ:", None))
        self.orientationLabel.setText(QCoreApplication.translate("WtykaFTP",
                                                                 u"Orientacja ----------------------------------------------------------------------------------",
                                                                 None))
        self.epsglabel3.setText(QCoreApplication.translate("WtykaFTP", u"Docelowy układ:", None))
        self.chooseQualityOrient.setItemText(0, QCoreApplication.translate("WtykaFTP", u"Ultra low", None))
        self.chooseQualityOrient.setItemText(1, QCoreApplication.translate("WtykaFTP", u"Low", None))
        self.chooseQualityOrient.setItemText(2, QCoreApplication.translate("WtykaFTP", u"Medium", None))
        self.chooseQualityOrient.setItemText(3, QCoreApplication.translate("WtykaFTP", u"High", None))
        self.chooseQualityOrient.setItemText(4, QCoreApplication.translate("WtykaFTP", u"Ultra high", None))

        self.allignmentLabel.setText(QCoreApplication.translate("WtykaFTP", u"Jakość wyrównania", None))
        self.productsLabel.setText(QCoreApplication.translate("WtykaFTP",
                                                              u"Produkty ------------------------------------------------------------------------------------",
                                                              None))
        self.cloudPointBox.setText(QCoreApplication.translate("WtykaFTP", u"Chmura", None))
        self.chooseQualityCloudPoint.setItemText(0, QCoreApplication.translate("WtykaFTP", u"Ultra low", None))
        self.chooseQualityCloudPoint.setItemText(1, QCoreApplication.translate("WtykaFTP", u"Low", None))
        self.chooseQualityCloudPoint.setItemText(2, QCoreApplication.translate("WtykaFTP", u"Medium", None))
        self.chooseQualityCloudPoint.setItemText(3, QCoreApplication.translate("WtykaFTP", u"High", None))
        self.chooseQualityCloudPoint.setItemText(4, QCoreApplication.translate("WtykaFTP", u"Ultra high", None))

        self.modelBox.setText(QCoreApplication.translate("WtykaFTP", u"Model", None))
        self.chooseQualityModel.setItemText(0, QCoreApplication.translate("WtykaFTP", u"Ultra low", None))
        self.chooseQualityModel.setItemText(1, QCoreApplication.translate("WtykaFTP", u"Low", None))
        self.chooseQualityModel.setItemText(2, QCoreApplication.translate("WtykaFTP", u"Medium", None))
        self.chooseQualityModel.setItemText(3, QCoreApplication.translate("WtykaFTP", u"High", None))
        self.chooseQualityModel.setItemText(4, QCoreApplication.translate("WtykaFTP", u"Ultra high", None))

        #self.rasterBox.setText(QCoreApplication.translate("WtykaFTP", u"Raster", None))
        self.runButton.setText(QCoreApplication.translate("WtykaFTP", u"Uruchom", None))